#!/bin/sh

con=`nmcli -t d | awk -F: '/wifi:/{print $4}'`
ssid=`./dmenus_base "$(nmcli -g ssid d w l | sed "s/^$con$/${DMENUS_CHAR:-*}$con/")"` || exit 0
nmcli d w c $ssid || nmcli d w c $ssid password `${DMENUS_CMD:-dmenu} -p password <&-`
